name: phonebook
description: "Projeto de catálogo telefônico com Flutter e gRPC"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.0.4
  protobuf: ^4.0.0
  fixnum: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
