include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**.g.dart'
    - 'lib/core/constant/l10n/gen/**'

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    directives_ordering: false