name: offline_first
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_cache_manager: ^3.3.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.1.0
  lottie: ^3.1.0
  path_provider: ^2.1.2


dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/core/constant/gen/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/

scripts:
  flutter-gen: fluttergen -c pubspec.yaml
  build-runner-one: flutter pub run build_runner build --delete-conflicting-outputs

