# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import phonebook_pb2 as phonebook__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in phonebook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhonebookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LookupNumber = channel.unary_unary(
                '/phonebook.PhonebookService/LookupNumber',
                request_serializer=phonebook__pb2.LookupRequest.SerializeToString,
                response_deserializer=phonebook__pb2.LookupResponse.FromString,
                _registered_method=True)


class PhonebookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LookupNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhonebookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LookupNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupNumber,
                    request_deserializer=phonebook__pb2.LookupRequest.FromString,
                    response_serializer=phonebook__pb2.LookupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phonebook.PhonebookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phonebook.PhonebookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PhonebookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LookupNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phonebook.PhonebookService/LookupNumber',
            phonebook__pb2.LookupRequest.SerializeToString,
            phonebook__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
